import { Category, Product, SiteSettings } from "@/types";

export const MOCK_SITE_SETTINGS: SiteSettings = {
  id: 1,
  deposit_percentage: 25,
  whatsapp_number: "201012345678",
  payment_instructions_ar:
    "طرق دفع العربون المتاحة:\n• فودافون كاش / المحافظ الإلكترونية: 01012345678\n• انستاباي (InstaPay): beit.eldallah@instapay\n• تحويل بنكي (البنك الأهلي المصري): 12345678901234\nيرجى إرسال لقطة شاشة لإيصال التحويل في رسالة الواتساب لتأكيد طلبك وبدء التجهيز.",
  payment_instructions_en:
    "Available Deposit Payment Methods:\n• Vodafone Cash / Smart Wallets: 01012345678\n• InstaPay: beit.eldallah@instapay\n• Bank Transfer (NBE): 12345678901234\nPlease send a screenshot of the transfer receipt in the WhatsApp chat to confirm your order.",
  store_name_ar: "بيت الدلة",
  store_name_en: "Beit El Dallah",
  logo_url: "/logo.svg",
  updated_at: new Date().toISOString(),
};

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    slug: "dallah-coffee",
    name_ar: "بن الدله",
    name_en: "Dallah Coffee",
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "cat-2",
    slug: "star-coffee",
    name_ar: "ستار كوفي",
    name_en: "Star Coffee",
    image_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "cat-3",
    slug: "espresso",
    name_ar: "اسبريسو",
    name_en: "Espresso",
    image_url: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?q=80&w=800&auto=format&fit=crop",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "cat-4",
    slug: "turkish-coffee",
    name_ar: "بن تركي",
    name_en: "Turkish Coffee",
    image_url: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=800&auto=format&fit=crop",
    sort_order: 4,
    is_active: true,
  },
  {
    id: "cat-5",
    slug: "tea",
    name_ar: "شاي",
    name_en: "Tea",
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop",
    sort_order: 5,
    is_active: true,
  },
  {
    id: "cat-6",
    slug: "cafe-supplies",
    name_ar: "مستلزمات الكافيهات",
    name_en: "Cafe Supplies",
    image_url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?q=80&w=800&auto=format&fit=crop",
    sort_order: 6,
    is_active: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    category_id: "cat-1",
    slug: "dallah-golden-blend",
    name_ar: "بن الدلة - الخلطة الذهبية الملكية",
    name_en: "Beit El Dallah - Royal Golden Blend",
    short_description_ar: "توليفة البن العربي الأصيل مع حبوب الهيل الفاخر وشعيرات الزعفران الطبيعي لنكهة خليجية مميزة.",
    short_description_en: "Authentic Arabic coffee blend infused with green cardamom and natural saffron threads for an exquisite royal cup.",
    base_price: 195.0,
    image_url_1: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    image_url_2: "https://images.unsplash.com/photo-1509785307050-d4066910ec1e?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    sort_order: 1,
    specs: [
      { label_ar: "درجة التحميص", label_en: "Roast Level", value_ar: "أشقر عربي فاتح", value_en: "Light Blonde Arabic" },
      { label_ar: "المكونات", label_en: "Ingredients", value_ar: "بن عربي، هيل، زعفران، قرنفل", value_en: "Arabic beans, Cardamom, Saffron, Cloves" },
      { label_ar: "المنشأ", label_en: "Origin", value_ar: "اليمن والبرازيل", value_en: "Yemen & Brazil" },
    ],
    variants: [
      { id: "var-1-1", product_id: "prod-1", attribute_type: "weight", attribute_value_ar: "250 جرام (250g)", attribute_value_en: "250g", price_override: 195.0, is_default: true },
      { id: "var-1-2", product_id: "prod-1", attribute_type: "weight", attribute_value_ar: "500 جرام (500g)", attribute_value_en: "500g", price_override: 370.0, is_default: false },
      { id: "var-1-3", product_id: "prod-1", attribute_type: "weight", attribute_value_ar: "1 كيلو (1kg)", attribute_value_en: "1kg", price_override: 710.0, is_default: false },
    ],
  },
  {
    id: "prod-2",
    category_id: "cat-2",
    slug: "star-house-blend",
    name_ar: "ستار كوفي - خلطة الدار المتوازنة",
    name_en: "Star Coffee - Signature House Blend",
    short_description_ar: "مزيج فريد متوازن بين الحلاوة الطبيعية والحموضة اللطيفة، مثالي لكل أوقات اليوم وطرق التحضير.",
    short_description_en: "A balanced signature blend featuring sweet chocolate notes and subtle citrus, crafted for all-day sipping.",
    base_price: 175.0,
    image_url_1: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop",
    image_url_2: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    sort_order: 2,
    specs: [
      { label_ar: "درجة التحميص", label_en: "Roast Level", value_ar: "وسط (Medium)", value_en: "Medium" },
      { label_ar: "الإيحاءات", label_en: "Notes", value_ar: "شوكولاتة داكنة، كراميل، مكسرات", value_en: "Dark Chocolate, Caramel, Roasted Nuts" },
    ],
    variants: [
      { id: "var-2-1", product_id: "prod-2", attribute_type: "weight", attribute_value_ar: "250 جرام (250g)", attribute_value_en: "250g", price_override: 175.0, is_default: true },
      { id: "var-2-2", product_id: "prod-2", attribute_type: "weight", attribute_value_ar: "500 جرام (500g)", attribute_value_en: "500g", price_override: 330.0, is_default: false },
      { id: "var-2-3", product_id: "prod-2", attribute_type: "weight", attribute_value_ar: "1 كيلو (1kg)", attribute_value_en: "1kg", price_override: 630.0, is_default: false },
    ],
  },
  {
    id: "prod-3",
    category_id: "cat-3",
    slug: "espresso-supremo",
    name_ar: "اسبريسو سوبريمو كولومبي",
    name_en: "Colombian Supremo Espresso",
    short_description_ar: "حبوب ارابيكا كولومبية 100% مع قوام حريري وكريما غنية ونكهة كاكاو مكثفة.",
    short_description_en: "100% Colombian Arabica delivering rich velvet crema, full body, and intense cacao finish.",
    base_price: 210.0,
    image_url_1: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?q=80&w=800&auto=format&fit=crop",
    image_url_2: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    sort_order: 3,
    specs: [
      { label_ar: "درجة التحميص", label_en: "Roast Level", value_ar: "وسط غامق (Medium Dark)", value_en: "Medium Dark" },
      { label_ar: "السلالة", label_en: "Varietal", value_ar: "كاستيلو، كاتورا", value_en: "Castillo, Caturra" },
    ],
    variants: [
      { id: "var-3-1", product_id: "prod-3", attribute_type: "weight", attribute_value_ar: "250 جرام (250g)", attribute_value_en: "250g", price_override: 210.0, is_default: true },
      { id: "var-3-2", product_id: "prod-3", attribute_type: "weight", attribute_value_ar: "500 جرام (500g)", attribute_value_en: "500g", price_override: 390.0, is_default: false },
      { id: "var-3-3", product_id: "prod-3", attribute_type: "weight", attribute_value_ar: "1 كيلو (1kg)", attribute_value_en: "1kg", price_override: 750.0, is_default: false },
    ],
  },
  {
    id: "prod-4",
    category_id: "cat-4",
    slug: "turkish-mastic-cardamom",
    name_ar: "بن تركي محوج بالهيل والمستكة الحرة",
    name_en: "Turkish Coffee with Cardamom & Mastic",
    short_description_ar: "مطحون ناعم كالحرير مع أجود أنواع الهيل الهندي وحبات المستكة اليونانية الأصلية.",
    short_description_en: "Silk-smooth grind infused with fragrant green cardamom and pure Greek Chios mastic.",
    base_price: 160.0,
    image_url_1: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=800&auto=format&fit=crop",
    image_url_2: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    sort_order: 4,
    specs: [
      { label_ar: "الطحنة", label_en: "Grind", value_ar: "فائقة النعومة (Extra Fine)", value_en: "Extra Fine" },
      { label_ar: "التحويجة", label_en: "Spices", value_ar: "هيل أخضر، مستكة، جوزة الطيب", value_en: "Cardamom, Mastic, Nutmeg" },
    ],
    variants: [
      { id: "var-4-1", product_id: "prod-4", attribute_type: "weight", attribute_value_ar: "200 جرام (200g)", attribute_value_en: "200g", price_override: 160.0, is_default: true },
      { id: "var-4-2", product_id: "prod-4", attribute_type: "weight", attribute_value_ar: "400 جرام (400g)", attribute_value_en: "400g", price_override: 300.0, is_default: false },
      { id: "var-4-3", product_id: "prod-4", attribute_type: "weight", attribute_value_ar: "1 كيلو (1kg)", attribute_value_en: "1kg", price_override: 700.0, is_default: false },
    ],
  },
  {
    id: "prod-5",
    category_id: "cat-5",
    slug: "ceylon-silver-leaf-tea",
    name_ar: "شاي سيلاني فاخر أوراق كاملة BOPF",
    name_en: "Premium Ceylon Full Leaf Tea BOPF",
    short_description_ar: "أوراق شاي سيلانية منتقاة يدوياً من مرتفعات سريلانكا، بلون عنبري نقي ونكهة غنية منعشة.",
    short_description_en: "Handpicked high-grown Ceylon tea leaves offering a sparkling amber cup with brisk aroma.",
    base_price: 120.0,
    image_url_1: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop",
    image_url_2: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    sort_order: 5,
    specs: [
      { label_ar: "النوع", label_en: "Type", value_ar: "شاي أسود نقي أوراق كاملة", value_en: "Pure Black Full Leaf Tea" },
      { label_ar: "المنشأ", label_en: "Origin", value_ar: "سيلان (سريلانكا)", value_en: "Ceylon (Sri Lanka)" },
    ],
    variants: [
      { id: "var-5-1", product_id: "prod-5", attribute_type: "weight", attribute_value_ar: "250 جرام (250g)", attribute_value_en: "250g", price_override: 120.0, is_default: true },
      { id: "var-5-2", product_id: "prod-5", attribute_type: "weight", attribute_value_ar: "500 جرام (500g)", attribute_value_en: "500g", price_override: 225.0, is_default: false },
    ],
  },
  {
    id: "prod-6",
    category_id: "cat-6",
    slug: "handmade-copper-cezve-size3",
    name_ar: "كنكة قهوة نحاس نقي يدوي - مقاس 3",
    name_en: "Handmade Pure Copper Cezve - Size 3",
    short_description_ar: "كنكة نحاسية مطروقة يدوياً مع مقبض خشبي عازل للحرارة وبطانة قصدير غذائي لتوزيع حراري متكامل.",
    short_description_en: "Hand-hammered heavy-gauge copper ibrik with insulated wooden handle and food-safe tin lining.",
    base_price: 285.0,
    image_url_1: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?q=80&w=800&auto=format&fit=crop",
    image_url_2: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    is_active: true,
    sort_order: 6,
    specs: [
      { label_ar: "المادة", label_en: "Material", value_ar: "نحاس أحمر أصلي سمك 1.5 مم", value_en: "Pure Red Copper 1.5mm" },
      { label_ar: "السعة", label_en: "Capacity", value_ar: "3 فناجين قهوة (220 مل)", value_en: "3 Cups (220ml)" },
    ],
    variants: [
      { id: "var-6-1", product_id: "prod-6", attribute_type: "size", attribute_value_ar: "مقاس 3 (3 فناجين)", attribute_value_en: "Size 3 (3 Cups)", price_override: 285.0, is_default: true },
      { id: "var-6-2", product_id: "prod-6", attribute_type: "size", attribute_value_ar: "مقاس 4 (4 فناجين)", attribute_value_en: "Size 4 (4 Cups)", price_override: 340.0, is_default: false },
    ],
  },
];
